import = [ "~/.config/alacritty/themes/themes/coolnight.toml" ]

[env]
TERM = "xterm-256color"

[window]
padding.x = 30
padding.y = 30

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
size = 15.0 

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

